<a href="https://colab.research.google.com/github/Ga-paulucci/Manipul-o-banco-de-dados/blob/main/Manipulando_banco_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importando bibliotecas e fazendo leitura do banco.

In [1]:
import pandas as pd
import sqlalchemy
dados_desafio = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
pd.read_csv(dados_desafio)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
438458,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,135000.0,0,Casa/apartamento próprio
438459,6840222,43,Ensino médio,Solteiro,1,Empregado,Construção Civil,8,103500.0,0,Casa/apartamento próprio
438460,6841878,22,Ensino superior,Solteiro,1,Associado comercial,Vendas,1,54000.0,0,Mora com os pais
438461,6842765,59,Ensino médio,Casado,2,Pensionista,Outro,0,72000.0,0,Casa/apartamento próprio
438462,6842885,51,Ensino médio,Casado,2,Empregado,Vendas,3,121500.0,0,Casa/apartamento próprio

Importando funções, criando banco local e dando nome para a tabela.

In [2]:
from sqlalchemy import MetaData, create_engine, inspect, Table

In [3]:
engine = create_engine('sqlite:///:memory:')
inspec = inspect(engine)
df_clientes_desafio = pd.read_csv(dados_desafio)
df_clientes_desafio.to_sql('clientes_desafio', engine, index=False)

438463

In [4]:
print(inspec.get_table_names())

['clientes_desafio']

Importando a biblioteca text para leitura direta das querys sql.

In [5]:
from sqlalchemy import text

Query para atualização do rendimento anual do cliente.

In [6]:
query = 'UPDATE clientes_desafio SET Rendimento_anual = 300000 WHERE ID_Cliente = 6840104'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

Consulta para confirmação da atualização do cliente.

In [7]:
query = 'SELECT * FROM clientes_desafio WHERE ID_Cliente = 6840104'
pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6840104,62,Ensino médio,Divorciado,1,Pensionista,Outro,0,300000.0,0,Casa/apartamento próprio

Query para deletar cliente do banco de dados.

In [8]:
query = 'DELETE FROM clientes_desafio WHERE ID_Cliente = 5008809'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

Consulta para confirmar o delete do cliente.

In [9]:
query = 'SELECT * FROM clientes_desafio WHERE ID_Cliente = 5008809'
pd.read_sql(query, engine)

Empty DataFrame
Columns: [ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia]
Index: []

Query para adicionar um cliente na tabela.

In [10]:
query = 'INSERT INTO clientes_desafio (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, Rendimento_anual, Tem_carro, Moradia) VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", 2, 290000, 0, "Casa/apartamento próprio")'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

Consulta para confirmar a entrada de todos os dados do novo cliente.

In [11]:
query = 'SELECT * FROM clientes_desafio WHERE ID_Cliente = 6850985'
pd.read_sql(query, engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,6850985,33,Doutorado,Solteiro,1,Empregado,TI,2,290000.0,0,Casa/apartamento próprio